### PR TITLE
Pronouns handler should make getfc nicer along with future messages

### PR DESCRIPTION
**Pull request by kjhf**
:)

btw this is untested because I don't have your Config object

### CODE REVIEW

**Comment by kjhf** [comment]
Just realised that the possessive will return Hers not Her for "Her friend code is ...", We're looking for a possessive adjective rather than a possessive pronoun.

**Comment by kjhf** [comment]
> Just realised that the possessive will return Hers not Her for "Her friend code is ...", We're looking for a possessive adjective rather than a possessive pronoun.

Fixed with latest commit

**Review by pentagramswheel — CHANGES_REQUESTED** [review]
Sorry for the late response Slate. Has this (latest commit) been tested? If not, would you mind testing it first?

You don't need `Config` to test this, because you can just use your `PronounsBuilder(String)` constructor to test it. I recommend testing through a `main` method within `PronounsBuilder` itself.

Last few things (my fault for getting back to this late), but I have since updated `Profile`, if you wouldn't mind pulling to prevent the merge conflict. You can also use `Events.RANDOM_GENERATOR` instead of making a new one.

**Comment by kjhf** [comment]
merged/synced fork with upstream.
I tested using your suggested main method, which I left in commented-out as requested.
Had to create the Config object in a separate file to compile the project. Maybe could add to the README, idk.
That looks like: 

```java
package bot;

public final class Config {
        public static final String mitProfilesSheetID = "";
        public static final String lpCyclesSheetID = "";
        public static final String ioCyclesSheetID = "";
        public static final String fsGradSheetID = "";
        public static final String lpGradSheetID = "";
        public static final String lpCyclesCalculationSheetID = "";
        public static final String ioGradSheetID = "";
        public static final String ioCyclesCalculationSheetID = "";
        public static final String botToken = "";
}
```

**Review by pentagramswheel — APPROVED** [review]
Looks good, may rearrange `main` testing for formal unit testing.

**Pull request merged**
